apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: verifytolerations
spec:
  crd:
    spec:
      names:
        kind: VerifyTolerations
        listKind: VerifyTolerationsList
        plural: verifytolerations
        singular: verifytolerations
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            nsname:
              type: string
            allowedtol: 
               type: string  
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package verifytolerations

        violation[{"msg": msg, "details": {"missing_labels"}}] {
          providedns := input.review.object.metadata.namespace
          requiredns := input.parameters.nsname
          providedtols := [ tols | tols := input.review.object.spec.template.spec.tolerations[j].value ]
          requiredtols := input.parameters.allowedtols
          providedtols[i] ==  requiredtols
          providedns !=  requiredns
          msg := sprintf("You cannot use %v toleration with %v namespace", [providedtols, providedns])
        }