apiVersion: constraints.gatekeeper.sh/v1beta1
kind: VerifyTolerations
metadata:
  name: restrict-appa-tols
spec:
  match:
    kinds:
      - apiGroups: ["","apps","extensions"]
        kinds: ["Deployment"]
  parameters:
    nsname: "app-a"
    allowedtols: "appa"